# Generated by ChatGPT
# bootstrap_kana_cards.py
from .database import maybe_connection_commit
from .kana_card import KanaCard

# ---------------------------------------------------------------------------
# Hiragana
# ---------------------------------------------------------------------------

KanaCard.create(kana="あ", romaji="a")
KanaCard.create(kana="い", romaji="i")
KanaCard.create(kana="う", romaji="u")
KanaCard.create(kana="え", romaji="e")
KanaCard.create(kana="お", romaji="o")

KanaCard.create(kana="か", romaji="ka")
KanaCard.create(kana="き", romaji="ki")
KanaCard.create(kana="く", romaji="ku")
KanaCard.create(kana="け", romaji="ke")
KanaCard.create(kana="こ", romaji="ko")

KanaCard.create(kana="さ", romaji="sa")
KanaCard.create(kana="し", romaji="shi")
KanaCard.create(kana="す", romaji="su")
KanaCard.create(kana="せ", romaji="se")
KanaCard.create(kana="そ", romaji="so")

KanaCard.create(kana="た", romaji="ta")
KanaCard.create(kana="ち", romaji="chi")
KanaCard.create(kana="つ", romaji="tsu")
KanaCard.create(kana="て", romaji="te")
KanaCard.create(kana="と", romaji="to")

KanaCard.create(kana="な", romaji="na")
KanaCard.create(kana="に", romaji="ni")
KanaCard.create(kana="ぬ", romaji="nu")
KanaCard.create(kana="ね", romaji="ne")
KanaCard.create(kana="の", romaji="no")

KanaCard.create(kana="は", romaji="ha")
KanaCard.create(kana="ひ", romaji="hi")
KanaCard.create(kana="ふ", romaji="fu")
KanaCard.create(kana="へ", romaji="he")
KanaCard.create(kana="ほ", romaji="ho")

KanaCard.create(kana="ま", romaji="ma")
KanaCard.create(kana="み", romaji="mi")
KanaCard.create(kana="む", romaji="mu")
KanaCard.create(kana="め", romaji="me")
KanaCard.create(kana="も", romaji="mo")

KanaCard.create(kana="や", romaji="ya")
KanaCard.create(kana="ゆ", romaji="yu")
KanaCard.create(kana="よ", romaji="yo")

KanaCard.create(kana="ら", romaji="ra")
KanaCard.create(kana="り", romaji="ri")
KanaCard.create(kana="る", romaji="ru")
KanaCard.create(kana="れ", romaji="re")
KanaCard.create(kana="ろ", romaji="ro")

KanaCard.create(kana="わ", romaji="wa")
KanaCard.create(kana="を", romaji="wo")
KanaCard.create(kana="ん", romaji="n")

# Dakuten / handakuten
KanaCard.create(kana="が", romaji="ga")
KanaCard.create(kana="ぎ", romaji="gi")
KanaCard.create(kana="ぐ", romaji="gu")
KanaCard.create(kana="げ", romaji="ge")
KanaCard.create(kana="ご", romaji="go")

KanaCard.create(kana="ざ", romaji="za")
KanaCard.create(kana="じ", romaji="ji")
KanaCard.create(kana="ず", romaji="zu")
KanaCard.create(kana="ぜ", romaji="ze")
KanaCard.create(kana="ぞ", romaji="zo")

KanaCard.create(kana="だ", romaji="da")
KanaCard.create(kana="ぢ", romaji="ji")
KanaCard.create(kana="づ", romaji="zu")
KanaCard.create(kana="で", romaji="de")
KanaCard.create(kana="ど", romaji="do")

KanaCard.create(kana="ば", romaji="ba")
KanaCard.create(kana="び", romaji="bi")
KanaCard.create(kana="ぶ", romaji="bu")
KanaCard.create(kana="べ", romaji="be")
KanaCard.create(kana="ぼ", romaji="bo")

KanaCard.create(kana="ぱ", romaji="pa")
KanaCard.create(kana="ぴ", romaji="pi")
KanaCard.create(kana="ぷ", romaji="pu")
KanaCard.create(kana="ぺ", romaji="pe")
KanaCard.create(kana="ぽ", romaji="po")

# Small kana (if you want them as separate cards)
KanaCard.create(kana="ぁ", romaji="a")
KanaCard.create(kana="ぃ", romaji="i")
KanaCard.create(kana="ぅ", romaji="u")
KanaCard.create(kana="ぇ", romaji="e")
KanaCard.create(kana="ぉ", romaji="o")
KanaCard.create(kana="ゃ", romaji="ya")
KanaCard.create(kana="ゅ", romaji="yu")
KanaCard.create(kana="ょ", romaji="yo")
KanaCard.create(kana="っ", romaji="tsu")

# ---------------------------------------------------------------------------
# Katakana
# ---------------------------------------------------------------------------

KanaCard.create(kana="ア", romaji="a")
KanaCard.create(kana="イ", romaji="i")
KanaCard.create(kana="ウ", romaji="u")
KanaCard.create(kana="エ", romaji="e")
KanaCard.create(kana="オ", romaji="o")

KanaCard.create(kana="カ", romaji="ka")
KanaCard.create(kana="キ", romaji="ki")
KanaCard.create(kana="ク", romaji="ku")
KanaCard.create(kana="ケ", romaji="ke")
KanaCard.create(kana="コ", romaji="ko")

KanaCard.create(kana="サ", romaji="sa")
KanaCard.create(kana="シ", romaji="shi")
KanaCard.create(kana="ス", romaji="su")
KanaCard.create(kana="セ", romaji="se")
KanaCard.create(kana="ソ", romaji="so")

KanaCard.create(kana="タ", romaji="ta")
KanaCard.create(kana="チ", romaji="chi")
KanaCard.create(kana="ツ", romaji="tsu")
KanaCard.create(kana="テ", romaji="te")
KanaCard.create(kana="ト", romaji="to")

KanaCard.create(kana="ナ", romaji="na")
KanaCard.create(kana="ニ", romaji="ni")
KanaCard.create(kana="ヌ", romaji="nu")
KanaCard.create(kana="ネ", romaji="ne")
KanaCard.create(kana="ノ", romaji="no")

KanaCard.create(kana="ハ", romaji="ha")
KanaCard.create(kana="ヒ", romaji="hi")
KanaCard.create(kana="フ", romaji="fu")
KanaCard.create(kana="ヘ", romaji="he")
KanaCard.create(kana="ホ", romaji="ho")

KanaCard.create(kana="マ", romaji="ma")
KanaCard.create(kana="ミ", romaji="mi")
KanaCard.create(kana="ム", romaji="mu")
KanaCard.create(kana="メ", romaji="me")
KanaCard.create(kana="モ", romaji="mo")

KanaCard.create(kana="ヤ", romaji="ya")
KanaCard.create(kana="ユ", romaji="yu")
KanaCard.create(kana="ヨ", romaji="yo")

KanaCard.create(kana="ラ", romaji="ra")
KanaCard.create(kana="リ", romaji="ri")
KanaCard.create(kana="ル", romaji="ru")
KanaCard.create(kana="レ", romaji="re")
KanaCard.create(kana="ロ", romaji="ro")

KanaCard.create(kana="ワ", romaji="wa")
KanaCard.create(kana="ヲ", romaji="wo")
KanaCard.create(kana="ン", romaji="n")

# Dakuten / handakuten
KanaCard.create(kana="ガ", romaji="ga")
KanaCard.create(kana="ギ", romaji="gi")
KanaCard.create(kana="グ", romaji="gu")
KanaCard.create(kana="ゲ", romaji="ge")
KanaCard.create(kana="ゴ", romaji="go")

KanaCard.create(kana="ザ", romaji="za")
KanaCard.create(kana="ジ", romaji="ji")
KanaCard.create(kana="ズ", romaji="zu")
KanaCard.create(kana="ゼ", romaji="ze")
KanaCard.create(kana="ゾ", romaji="zo")

KanaCard.create(kana="ダ", romaji="da")
KanaCard.create(kana="ヂ", romaji="ji")
KanaCard.create(kana="ヅ", romaji="zu")
KanaCard.create(kana="デ", romaji="de")
KanaCard.create(kana="ド", romaji="do")

KanaCard.create(kana="バ", romaji="ba")
KanaCard.create(kana="ビ", romaji="bi")
KanaCard.create(kana="ブ", romaji="bu")
KanaCard.create(kana="ベ", romaji="be")
KanaCard.create(kana="ボ", romaji="bo")

KanaCard.create(kana="パ", romaji="pa")
KanaCard.create(kana="ピ", romaji="pi")
KanaCard.create(kana="プ", romaji="pu")
KanaCard.create(kana="ペ", romaji="pe")
KanaCard.create(kana="ポ", romaji="po")

# Small katakana (optional)
KanaCard.create(kana="ァ", romaji="a")
KanaCard.create(kana="ィ", romaji="i")
KanaCard.create(kana="ゥ", romaji="u")
KanaCard.create(kana="ェ", romaji="e")
KanaCard.create(kana="ォ", romaji="o")
KanaCard.create(kana="ャ", romaji="ya")
KanaCard.create(kana="ュ", romaji="yu")
KanaCard.create(kana="ョ", romaji="yo")
KanaCard.create(kana="ッ", romaji="tsu")

with maybe_connection_commit(None) as con:
    for kc in KanaCard.every():
        kc.sync(con)
